version: '3'

services:
  app:
    build: .
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    restart: always
  db:
    image: mongo
    container_name: database
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: reserva_db
    volumes:
      - ./dbdata:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://db:27017
    depends_on:
      - db
    links:
      - db
    ports:
      - "8081:8081"